export interface Conference {
  name: string;
  nameKo?: string;
  startDate: string; // ISO date string YYYY-MM-DD
  endDate: string;
  location: string;
  country: string;
  tags: string[];
  website?: string;
  isKorean: boolean;
  dateConfirmed?: boolean; // false = 날짜 미정 (작년 기준 월 포지셔닝)
}

export const CONFERENCES: Conference[] = [
  // ── 2026 ──
  {
    name: "AAAAI Annual Meeting 2026",
    startDate: "2026-02-27",
    endDate: "2026-03-02",
    location: "San Diego, CA, USA",
    country: "USA",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://annualmeeting.aaaai.org/",
    isKorean: false,
  },
  {
    name: "CIS Annual Meeting 2026",
    startDate: "2026-05-06",
    endDate: "2026-05-09",
    location: "New Orleans, LA, USA",
    country: "USA",
    tags: ["Immunodeficiency", "Immunology"],
    website: "https://cis.clinimmsoc.org/education/meetings/am26",
    isKorean: false,
  },
  {
    name: "KAAACI International Congress 2026",
    nameKo: "대한천식알레르기학회 국제학술대회",
    startDate: "2026-05-07",
    endDate: "2026-05-09",
    location: "Seoul, Korea",
    country: "Korea",
    tags: ["Asthma", "Allergy", "Immunology"],
    website: "https://www.kaaaci.or.kr/2026s/",
    isKorean: true,
  },
  {
    name: "ATS International Conference 2026",
    startDate: "2026-05-15",
    endDate: "2026-05-20",
    location: "Orlando, FL, USA",
    country: "USA",
    tags: ["Respiratory", "Asthma"],
    website: "https://site.thoracic.org/conference",
    isKorean: false,
  },
  {
    name: "대한소아알레르기호흡기학회 춘계학술대회 2026",
    nameKo: "대한소아알레르기호흡기학회 춘계학술대회",
    startDate: "2026-05-01",
    endDate: "2026-05-01",
    location: "TBD",
    country: "Korea",
    tags: ["Pediatric", "Allergy", "Respiratory"],
    website: "https://www.kapard.or.kr/",
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "EAACI Congress 2026",
    startDate: "2026-06-12",
    endDate: "2026-06-15",
    location: "Istanbul, Turkiye",
    country: "Turkiye",
    tags: ["Allergy", "Immunology"],
    website: "https://eaaci.org/events_congress/eaaci-congress-2026/",
    isKorean: false,
  },
  {
    name: "ERS International Congress 2026",
    startDate: "2026-09-05",
    endDate: "2026-09-09",
    location: "Barcelona, Spain",
    country: "Spain",
    tags: ["Respiratory", "Asthma"],
    website: "https://www.ersnet.org/events/ers-congress-2026/",
    isKorean: false,
  },
  {
    name: "대한소아알레르기호흡기학회 추계학술대회 2026",
    nameKo: "대한소아알레르기호흡기학회 추계학술대회",
    startDate: "2026-10-01",
    endDate: "2026-10-01",
    location: "TBD",
    country: "Korea",
    tags: ["Pediatric", "Allergy", "Respiratory"],
    website: "https://www.kapard.or.kr/",
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "ESID 22nd Biennial Meeting 2026",
    startDate: "2026-10-14",
    endDate: "2026-10-17",
    location: "Maastricht, Netherlands",
    country: "Netherlands",
    tags: ["Immunodeficiency", "Immunology"],
    website: "https://esidmeeting.org/",
    isKorean: false,
  },
  {
    name: "JSA/WAO/APAPARI Joint Congress 2026",
    nameKo: "일본알레르기학회/세계알레르기기구/APAPARI 합동학술대회",
    startDate: "2026-10-15",
    endDate: "2026-10-18",
    location: "Kyoto, Japan",
    country: "Japan",
    tags: ["Allergy", "Immunology"],
    website: "https://site2.convention.co.jp/jsa2026/en/",
    isKorean: false,
  },
  {
    name: "CSACI 81st Annual Scientific Meeting 2026",
    startDate: "2026-10-15",
    endDate: "2026-10-18",
    location: "Toronto, Canada",
    country: "Canada",
    tags: ["Allergy", "Immunology"],
    website: "https://am.csaci.ca/",
    isKorean: false,
  },
  {
    name: "대한알레르기학회 추계학술대회 2026",
    nameKo: "대한알레르기학회 추계학술대회",
    startDate: "2026-11-01",
    endDate: "2026-11-01",
    location: "TBD",
    country: "Korea",
    tags: ["Allergy", "Immunology"],
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "ACAAI Annual Scientific Meeting 2026",
    startDate: "2026-11-12",
    endDate: "2026-11-16",
    location: "Phoenix, AZ, USA",
    country: "USA",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://annualmeeting.acaai.org/2026/",
    isKorean: false,
  },
  {
    name: "APAAACI Congress 2026",
    startDate: "2026-12-04",
    endDate: "2026-12-06",
    location: "Ho Chi Minh City, Vietnam",
    country: "Vietnam",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://www.apaaaci2026.com/",
    isKorean: false,
  },

  // ── 2027 ──
  {
    name: "AAAAI Annual Meeting 2027",
    startDate: "2027-02-19",
    endDate: "2027-02-22",
    location: "New Orleans, LA, USA",
    country: "USA",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://annualmeeting.aaaai.org/attendee/future-dates-locations",
    isKorean: false,
  },
  {
    name: "CIS Annual Meeting 2027",
    startDate: "2027-04-14",
    endDate: "2027-04-17",
    location: "Denver, CO, USA",
    country: "USA",
    tags: ["Immunodeficiency", "Immunology"],
    website: "https://clinimmsoc.org/",
    isKorean: false,
  },
  {
    name: "대한천식알레르기학회 춘계학술대회 2027",
    nameKo: "대한천식알레르기학회 춘계학술대회",
    startDate: "2027-04-01",
    endDate: "2027-04-01",
    location: "TBD",
    country: "Korea",
    tags: ["Asthma", "Allergy"],
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "ATS International Conference 2027",
    startDate: "2027-05-01",
    endDate: "2027-05-01",
    location: "TBD, USA",
    country: "USA",
    tags: ["Respiratory", "Asthma"],
    website: "https://www.thoracic.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "대한소아알레르기호흡기학회 춘계학술대회 2027",
    nameKo: "대한소아알레르기호흡기학회 춘계학술대회",
    startDate: "2027-05-01",
    endDate: "2027-05-01",
    location: "TBD",
    country: "Korea",
    tags: ["Pediatric", "Allergy", "Respiratory"],
    website: "https://www.kapard.or.kr/",
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "EAACI Congress 2027",
    startDate: "2027-06-01",
    endDate: "2027-06-01",
    location: "TBD",
    country: "TBD",
    tags: ["Allergy", "Immunology"],
    website: "https://eaaci.org",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "ERS International Congress 2027",
    startDate: "2027-09-11",
    endDate: "2027-09-15",
    location: "Milan, Italy",
    country: "Italy",
    tags: ["Respiratory", "Asthma"],
    website: "https://www.ersnet.org/",
    isKorean: false,
  },
  {
    name: "IES 14th Biennial Congress 2027",
    startDate: "2027-10-01",
    endDate: "2027-10-01",
    location: "TBD",
    country: "TBD",
    tags: ["Eosinophil", "Immunology"],
    website: "https://www.eosinophil-society.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "대한알레르기학회 추계학술대회 2027",
    nameKo: "대한알레르기학회 추계학술대회",
    startDate: "2027-11-01",
    endDate: "2027-11-01",
    location: "TBD",
    country: "Korea",
    tags: ["Allergy", "Immunology"],
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "ACAAI Annual Scientific Meeting 2027",
    startDate: "2027-11-11",
    endDate: "2027-11-15",
    location: "Nashville, TN, USA",
    country: "USA",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://acaai.org/",
    isKorean: false,
  },
];
