export interface Conference {
  name: string;
  nameKo?: string;
  startDate: string; // ISO date string YYYY-MM-DD
  endDate: string;
  location: string;
  country: string;
  tags: string[];
  website?: string;
  isKorean: boolean;
  dateConfirmed?: boolean; // false = 날짜 미정 (작년 기준 월 포지셔닝)
}

export const CONFERENCES: Conference[] = [
  // ── 2025 ──
  {
    name: "ATS International Conference 2025",
    startDate: "2025-05-16",
    endDate: "2025-05-21",
    location: "San Francisco, CA, USA",
    country: "USA",
    tags: ["Respiratory", "Asthma"],
    website: "https://www.thoracic.org/",
    isKorean: false,
  },
  {
    name: "대한소아알레르기호흡기학회 춘계학술대회",
    nameKo: "대한소아알레르기호흡기학회 춘계학술대회",
    startDate: "2025-05-16",
    endDate: "2025-05-17",
    location: "TBD",
    country: "Korea",
    tags: ["Pediatric", "Allergy", "Respiratory"],
    website: "https://www.kapard.or.kr/",
    isKorean: true,
  },
  {
    name: "EAACI Congress 2025",
    startDate: "2025-06-20",
    endDate: "2025-06-23",
    location: "Helsinki, Finland",
    country: "Finland",
    tags: ["Allergy", "Immunology"],
    website: "https://eaaci.org",
    isKorean: false,
  },
  {
    name: "ERS International Congress 2025",
    startDate: "2025-09-13",
    endDate: "2025-09-17",
    location: "Madrid, Spain",
    country: "Spain",
    tags: ["Respiratory", "Asthma"],
    website: "https://www.ersnet.org/",
    isKorean: false,
  },
  {
    name: "대한알레르기학회 추계학술대회",
    nameKo: "대한알레르기학회 추계학술대회",
    startDate: "2025-10-31",
    endDate: "2025-11-01",
    location: "TBD",
    country: "Korea",
    tags: ["Allergy", "Immunology"],
    isKorean: true,
  },
  {
    name: "대한소아알레르기호흡기학회 추계학술대회",
    nameKo: "대한소아알레르기호흡기학회 추계학술대회",
    startDate: "2025-10-01",
    endDate: "2025-10-01",
    location: "TBD",
    country: "Korea",
    tags: ["Pediatric", "Allergy", "Respiratory"],
    website: "https://www.kapard.or.kr/",
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "CSACI Annual Scientific Meeting 2025",
    startDate: "2025-10-23",
    endDate: "2025-10-26",
    location: "TBD, Canada",
    country: "Canada",
    tags: ["Allergy", "Immunology"],
    website: "https://csaci.ca/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "JSACI Annual Meeting 2025",
    nameKo: "일본알레르기학회 학술대회",
    startDate: "2025-10-01",
    endDate: "2025-10-03",
    location: "TBD, Japan",
    country: "Japan",
    tags: ["Allergy", "Immunology"],
    website: "https://www.jsaweb.jp/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "ESID Biennial Meeting 2025",
    startDate: "2025-10-15",
    endDate: "2025-10-18",
    location: "TBD, Europe",
    country: "TBD",
    tags: ["Immunodeficiency", "Immunology"],
    website: "https://esid.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "CIS Annual Meeting 2025",
    startDate: "2025-05-29",
    endDate: "2025-05-31",
    location: "TBD, USA",
    country: "USA",
    tags: ["Immunodeficiency", "Immunology"],
    website: "https://www.clinimmsoc.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "ACAAI Annual Scientific Meeting 2025",
    startDate: "2025-11-06",
    endDate: "2025-11-10",
    location: "Anaheim, CA, USA",
    country: "USA",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://acaai.org/",
    isKorean: false,
  },
  {
    name: "ENDA Meeting 2025",
    startDate: "2025-10-01",
    endDate: "2025-10-03",
    location: "TBD, Europe",
    country: "TBD",
    tags: ["Drug Allergy", "Allergy"],
    website: "https://eaaci.org/",
    isKorean: false,
    dateConfirmed: false,
  },

  // ── 2026 ──
  {
    name: "AAAAI Annual Meeting 2026",
    startDate: "2026-02-27",
    endDate: "2026-03-02",
    location: "San Diego, CA, USA",
    country: "USA",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://www.aaaai.org",
    isKorean: false,
  },
  {
    name: "대한천식알레르기학회 춘계학술대회 2026",
    nameKo: "대한천식알레르기학회 춘계학술대회",
    startDate: "2026-04-01",
    endDate: "2026-04-01",
    location: "TBD",
    country: "Korea",
    tags: ["Asthma", "Allergy"],
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "ATS International Conference 2026",
    startDate: "2026-05-15",
    endDate: "2026-05-20",
    location: "TBD, USA",
    country: "USA",
    tags: ["Respiratory", "Asthma"],
    website: "https://www.thoracic.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "대한소아알레르기호흡기학회 춘계학술대회 2026",
    nameKo: "대한소아알레르기호흡기학회 춘계학술대회",
    startDate: "2026-05-01",
    endDate: "2026-05-01",
    location: "TBD",
    country: "Korea",
    tags: ["Pediatric", "Allergy", "Respiratory"],
    website: "https://www.kapard.or.kr/",
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "EAACI Congress 2026",
    startDate: "2026-06-12",
    endDate: "2026-06-15",
    location: "TBD",
    country: "TBD",
    tags: ["Allergy", "Immunology"],
    website: "https://eaaci.org",
    isKorean: false,
  },
  {
    name: "ERS International Congress 2026",
    startDate: "2026-09-01",
    endDate: "2026-09-01",
    location: "TBD, Europe",
    country: "TBD",
    tags: ["Respiratory", "Asthma"],
    website: "https://www.ersnet.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "WAO WISC 2026",
    startDate: "2026-10-01",
    endDate: "2026-10-04",
    location: "TBD",
    country: "TBD",
    tags: ["Allergy", "Immunology"],
    website: "https://www.worldallergy.org",
    isKorean: false,
  },
  {
    name: "APAAACI Congress 2026",
    startDate: "2026-10-01",
    endDate: "2026-10-04",
    location: "TBD, Asia Pacific",
    country: "TBD",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://apaaaci.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "대한알레르기학회 추계학술대회 2026",
    nameKo: "대한알레르기학회 추계학술대회",
    startDate: "2026-11-01",
    endDate: "2026-11-01",
    location: "TBD",
    country: "Korea",
    tags: ["Allergy", "Immunology"],
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "대한소아알레르기호흡기학회 추계학술대회 2026",
    nameKo: "대한소아알레르기호흡기학회 추계학술대회",
    startDate: "2026-10-01",
    endDate: "2026-10-01",
    location: "TBD",
    country: "Korea",
    tags: ["Pediatric", "Allergy", "Respiratory"],
    website: "https://www.kapard.or.kr/",
    isKorean: true,
    dateConfirmed: false,
  },
  {
    name: "JSACI Annual Meeting 2026",
    nameKo: "일본알레르기학회 학술대회",
    startDate: "2026-10-01",
    endDate: "2026-10-03",
    location: "TBD, Japan",
    country: "Japan",
    tags: ["Allergy", "Immunology"],
    website: "https://www.jsaweb.jp/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "CSACI Annual Scientific Meeting 2026",
    startDate: "2026-10-01",
    endDate: "2026-10-04",
    location: "TBD, Canada",
    country: "Canada",
    tags: ["Allergy", "Immunology"],
    website: "https://csaci.ca/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "ESID Biennial Meeting 2026",
    startDate: "2026-10-01",
    endDate: "2026-10-04",
    location: "TBD, Europe",
    country: "TBD",
    tags: ["Immunodeficiency", "Immunology"],
    website: "https://esid.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "CIS Annual Meeting 2026",
    startDate: "2026-05-01",
    endDate: "2026-05-03",
    location: "TBD, USA",
    country: "USA",
    tags: ["Immunodeficiency", "Immunology"],
    website: "https://www.clinimmsoc.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "ENDA Meeting 2026",
    startDate: "2026-10-01",
    endDate: "2026-10-03",
    location: "TBD, Europe",
    country: "TBD",
    tags: ["Drug Allergy", "Allergy"],
    website: "https://eaaci.org/",
    isKorean: false,
    dateConfirmed: false,
  },
  {
    name: "ACAAI Annual Scientific Meeting 2026",
    startDate: "2026-11-01",
    endDate: "2026-11-05",
    location: "TBD, USA",
    country: "USA",
    tags: ["Allergy", "Asthma", "Immunology"],
    website: "https://acaai.org/",
    isKorean: false,
    dateConfirmed: false,
  },
];
