export interface JournalConfig {
  name: string;
  abbreviation: string;
  issn: string;
  eIssn: string | null;
  impactFactor: number | null;
  color: string;
  slug: string;
  pubmedQuery: string;
}

export const JOURNALS: JournalConfig[] = [
  {
    name: "Allergy",
    abbreviation: "Allergy",
    issn: "0105-4538",
    eIssn: "1398-9995",
    impactFactor: 12.0,
    color: "#DC2626",
    slug: "allergy",
    pubmedQuery: '"Allergy"[ta] AND "0105-4538"[is]',
  },
  {
    name: "Clinical Reviews in Allergy & Immunology",
    abbreviation: "Clin Rev Allergy Immunol",
    issn: "1080-0549",
    eIssn: "1559-0267",
    impactFactor: 11.3,
    color: "#7C3AED",
    slug: "clin-rev-allergy-immunol",
    pubmedQuery: '"Clin Rev Allergy Immunol"[ta]',
  },
  {
    name: "Journal of Allergy and Clinical Immunology",
    abbreviation: "J Allergy Clin Immunol",
    issn: "0091-6749",
    eIssn: "1097-6825",
    impactFactor: 11.2,
    color: "#1E40AF",
    slug: "jaci",
    pubmedQuery: '"J Allergy Clin Immunol"[ta] NOT "Pract"[ta] NOT "Glob"[ta]',
  },
  {
    name: "Allergology International",
    abbreviation: "Allergol Int",
    issn: "1323-8930",
    eIssn: "1440-1592",
    impactFactor: 6.7,
    color: "#2563EB",
    slug: "allergology-international",
    pubmedQuery: '"Allergol Int"[ta]',
  },
  {
    name: "Journal of Allergy and Clinical Immunology: In Practice",
    abbreviation: "J Allergy Clin Immunol Pract",
    issn: "2213-2198",
    eIssn: "2213-2201",
    impactFactor: 6.6,
    color: "#3B82F6",
    slug: "jaci-in-practice",
    pubmedQuery: '"J Allergy Clin Immunol Pract"[ta]',
  },
  {
    name: "Clinical and Experimental Allergy",
    abbreviation: "Clin Exp Allergy",
    issn: "0954-7894",
    eIssn: "1365-2222",
    impactFactor: 5.2,
    color: "#F59E0B",
    slug: "clin-exp-allergy",
    pubmedQuery: '"Clin Exp Allergy"[ta]',
  },
  {
    name: "Journal of Investigational Allergology and Clinical Immunology",
    abbreviation: "J Investig Allergol Clin Immunol",
    issn: "1018-9068",
    eIssn: null,
    impactFactor: 4.8,
    color: "#0EA5E9",
    slug: "j-investig-allergol-clin-immunol",
    pubmedQuery: '"J Investig Allergol Clin Immunol"[ta]',
  },
  {
    name: "Annals of Allergy Asthma & Immunology",
    abbreviation: "Ann Allergy Asthma Immunol",
    issn: "1081-1206",
    eIssn: "1534-4436",
    impactFactor: 4.7,
    color: "#10B981",
    slug: "annals-allergy",
    pubmedQuery: '"Ann Allergy Asthma Immunol"[ta]',
  },
  {
    name: "Current Allergy and Asthma Reports",
    abbreviation: "Curr Allergy Asthma Rep",
    issn: "1529-7322",
    eIssn: "1534-6315",
    impactFactor: 4.6,
    color: "#14B8A6",
    slug: "curr-allergy-asthma-rep",
    pubmedQuery: '"Curr Allergy Asthma Rep"[ta]',
  },
  {
    name: "Contact Dermatitis",
    abbreviation: "Contact Dermatitis",
    issn: "0105-1873",
    eIssn: "1600-0536",
    impactFactor: 4.6,
    color: "#059669",
    slug: "contact-dermatitis",
    pubmedQuery: '"Contact Dermatitis"[ta]',
  },
  {
    name: "Pediatric Allergy and Immunology",
    abbreviation: "Pediatr Allergy Immunol",
    issn: "0905-6157",
    eIssn: "1399-3038",
    impactFactor: 4.5,
    color: "#22C55E",
    slug: "pediatric-allergy-immunology",
    pubmedQuery: '"Pediatr Allergy Immunol"[ta]',
  },
  {
    name: "World Allergy Organization Journal",
    abbreviation: "World Allergy Organ J",
    issn: "1939-4551",
    eIssn: null,
    impactFactor: 4.3,
    color: "#65A30D",
    slug: "world-allergy-organization-journal",
    pubmedQuery: '"World Allergy Organ J"[ta]',
  },
  {
    name: "Allergy Asthma & Immunology Research",
    abbreviation: "Allergy Asthma Immunol Res",
    issn: "2092-7355",
    eIssn: "2092-7363",
    impactFactor: 4.3,
    color: "#84CC16",
    slug: "allergy-asthma-immunology-research",
    pubmedQuery: '"Allergy Asthma Immunol Res"[ta]',
  },
  {
    name: "Clinical and Translational Allergy",
    abbreviation: "Clin Transl Allergy",
    issn: "2045-7022",
    eIssn: null,
    impactFactor: 4.0,
    color: "#D97706",
    slug: "clin-transl-allergy",
    pubmedQuery: '"Clin Transl Allergy"[ta]',
  },
  {
    name: "Journal of Asthma and Allergy",
    abbreviation: "J Asthma Allergy",
    issn: "1178-6965",
    eIssn: null,
    impactFactor: 3.0,
    color: "#F97316",
    slug: "journal-asthma-allergy",
    pubmedQuery: '"J Asthma Allergy"[ta]',
  },
  {
    name: "Current Opinion in Allergy and Clinical Immunology",
    abbreviation: "Curr Opin Allergy Clin Immunol",
    issn: "1528-4050",
    eIssn: "1473-6322",
    impactFactor: 2.6,
    color: "#8B5CF6",
    slug: "curr-op-allergy-clin-immunol",
    pubmedQuery: '"Curr Opin Allergy Clin Immunol"[ta]',
  },
  {
    name: "Allergy Asthma and Clinical Immunology",
    abbreviation: "Allergy Asthma Clin Immunol",
    issn: "1710-1484",
    eIssn: "1710-1492",
    impactFactor: 2.4,
    color: "#A855F7",
    slug: "allergy-asthma-clin-immunol",
    pubmedQuery: '"Allergy Asthma Clin Immunol"[ta]',
  },
  {
    name: "Allergy and Asthma Proceedings",
    abbreviation: "Allergy Asthma Proc",
    issn: "1088-5412",
    eIssn: "1539-6304",
    impactFactor: 2.2,
    color: "#EC4899",
    slug: "allergy-asthma-proc",
    pubmedQuery: '"Allergy Asthma Proc"[ta]',
  },
  {
    name: "Immunology and Allergy Clinics of North America",
    abbreviation: "Immunol Allergy Clin North Am",
    issn: "0889-8561",
    eIssn: "1557-8607",
    impactFactor: 2.2,
    color: "#E11D48",
    slug: "immunol-allergy-clin-north-am",
    pubmedQuery: '"Immunol Allergy Clin North Am"[ta]',
  },
  {
    name: "Allergologia et Immunopathologia",
    abbreviation: "Allergol Immunopathol (Madr)",
    issn: "0301-0546",
    eIssn: "1578-1267",
    impactFactor: 2.1,
    color: "#EF4444",
    slug: "allergol-immunopathol-madr",
    pubmedQuery: '"Allergol Immunopathol (Madr)"[ta]',
  },
  {
    name: "Asian Pacific Journal of Allergy and Immunology",
    abbreviation: "Asian Pac J Allergy Immunol",
    issn: "0125-877X",
    eIssn: null,
    impactFactor: 1.9,
    color: "#0D9488",
    slug: "asian-pac-j-allergy-immunol",
    pubmedQuery: '"Asian Pac J Allergy Immunol"[ta]',
  },
  {
    name: "International Archives of Allergy and Immunology",
    abbreviation: "Int Arch Allergy Immunol",
    issn: "1018-2438",
    eIssn: "1423-0097",
    impactFactor: null,
    color: "#8B5CF6",
    slug: "int-arch-allergy",
    pubmedQuery: '"Int Arch Allergy Immunol"[ta]',
  },
  {
    name: "JACI: Global",
    abbreviation: "J Allergy Clin Immunol Glob",
    issn: "2772-8293",
    eIssn: null,
    impactFactor: 2.41,
    color: "#60A5FA",
    slug: "jaci-global",
    pubmedQuery: '"J Allergy Clin Immunol Glob"[ta]',
  },
];
