import { NextRequest, NextResponse } from "next/server";
import { createAnonClient, createServiceClient } from "@/lib/supabase/server";
import { rateLimit } from "@/lib/utils/rate-limit";
import {
  computeAuthorGeography,
  type AuthorGeographyResult,
} from "@/lib/insights/author-geography";
import type { Json } from "@/types/supabase";

const limiter = rateLimit({ windowMs: 60_000, maxRequests: 10 });

export const dynamic = "force-dynamic";
export const maxDuration = 30;

const CACHE_HEADER = "public, s-maxage=3600, stale-while-revalidate=86400";

/**
 * Upsert a freshly computed result into geography_insights so subsequent
 * requests hit the fast path. Best-effort: a failure here (e.g. the table
 * not yet migrated) must not break the response.
 */
async function persistSnapshot(result: AuthorGeographyResult): Promise<void> {
  try {
    const service = createServiceClient();
    await service
      .from("geography_insights")
      .upsert(
        {
          days: result.days,
          from_date: result.fromDate,
          total_first_authors: result.totalFirstAuthors,
          locations: result.locations as unknown as Json,
          computed_at: new Date().toISOString(),
        },
        { onConflict: "days" },
      );
  } catch (error) {
    console.warn("[author-geography] snapshot persist skipped:", error);
  }
}

export async function GET(request: NextRequest) {
  const ip = request.headers.get("x-forwarded-for")?.split(",")[0].trim() || "unknown";
  const { success } = limiter.check(ip);
  if (!success) {
    return NextResponse.json({ error: "Too many requests" }, { status: 429 });
  }

  const searchParams = request.nextUrl.searchParams;
  const requestedDays = Number(searchParams.get("days") || process.env.CRON_SYNC_DAYS || "180");
  const days =
    Number.isFinite(requestedDays) && requestedDays >= 1
      ? Math.min(Math.floor(requestedDays), 365)
      : 180;

  const supabase = createAnonClient();

  // Fast path: serve the daily precomputed snapshot (generated by the
  // generate-geography-insights Inngest cron).
  const { data: snapshot } = await supabase
    .from("geography_insights")
    .select("days, computed_at, from_date, total_first_authors, locations")
    .eq("days", days)
    .maybeSingle();

  if (snapshot) {
    const response = NextResponse.json({
      source: "precomputed",
      days: snapshot.days,
      asOf: snapshot.computed_at,
      fromDate: snapshot.from_date,
      totalFirstAuthors: snapshot.total_first_authors,
      locations: snapshot.locations ?? [],
    });
    response.headers.set("Cache-Control", CACHE_HEADER);
    return response;
  }

  // Fallback: compute live. Reached before the first cron run, or for a
  // non-standard `days` value the cron does not precompute. Use the service
  // client — the anon role's tight statement timeout cancels the multi-page
  // aggregation, while the service role has a generous one (same client the
  // cron uses).
  try {
    const result = await computeAuthorGeography(createServiceClient(), days);
    // Seed the snapshot so the next request takes the fast path without
    // waiting for the daily cron. Best-effort — never fails the response.
    await persistSnapshot(result);
    const response = NextResponse.json({
      source: "database",
      days: result.days,
      asOf: new Date().toISOString(),
      fromDate: result.fromDate,
      totalFirstAuthors: result.totalFirstAuthors,
      locations: result.locations,
    });
    response.headers.set("Cache-Control", CACHE_HEADER);
    return response;
  } catch (error) {
    console.error("[author-geography] live computation failed:", error);
    return NextResponse.json(
      { error: "Failed to fetch first-author affiliations." },
      { status: 500 }
    );
  }
}
