import { NextRequest, NextResponse } from "next/server";
import { createAnonClient, createServiceClient } from "@/lib/supabase/server";
import { rateLimit } from "@/lib/utils/rate-limit";
import {
  computeAuthorGeography,
  type AuthorGeographyResult,
} from "@/lib/insights/author-geography";

const limiter = rateLimit({ windowMs: 60_000, maxRequests: 10 });

export const dynamic = "force-dynamic";
export const maxDuration = 30;

const CACHE_HEADER = "public, s-maxage=3600, stale-while-revalidate=86400";

interface GeographySnapshot {
  days: number;
  computed_at: string;
  from_date: string;
  total_first_authors: number;
  locations: unknown;
}

/**
 * Upsert a freshly computed result into geography_insights so subsequent
 * requests hit the fast path. Best-effort: a failure here (e.g. the table
 * not yet migrated) must not break the response. geography_insights is not
 * in the generated Supabase types yet, so the write is cast.
 */
async function persistSnapshot(result: AuthorGeographyResult): Promise<void> {
  try {
    const service = createServiceClient();
    await (service as unknown as {
      from: (table: string) => {
        upsert: (
          values: Record<string, unknown>,
          options: { onConflict: string },
        ) => Promise<{ error: unknown }>;
      };
    })
      .from("geography_insights")
      .upsert(
        {
          days: result.days,
          from_date: result.fromDate,
          total_first_authors: result.totalFirstAuthors,
          locations: result.locations,
          computed_at: new Date().toISOString(),
        },
        { onConflict: "days" },
      );
  } catch (error) {
    console.warn("[author-geography] snapshot persist skipped:", error);
  }
}

export async function GET(request: NextRequest) {
  const ip = request.headers.get("x-forwarded-for")?.split(",")[0].trim() || "unknown";
  const { success } = limiter.check(ip);
  if (!success) {
    return NextResponse.json({ error: "Too many requests" }, { status: 429 });
  }

  const searchParams = request.nextUrl.searchParams;
  const requestedDays = Number(searchParams.get("days") || process.env.CRON_SYNC_DAYS || "180");
  const days =
    Number.isFinite(requestedDays) && requestedDays >= 1
      ? Math.min(Math.floor(requestedDays), 365)
      : 180;

  const supabase = createAnonClient();

  // Fast path: serve the daily precomputed snapshot (generated by the
  // generate-geography-insights Inngest cron). geography_insights is not in the
  // generated Supabase types yet, so the query is cast.
  const { data: snapshot } = await (supabase as unknown as {
    from: (table: string) => {
      select: (cols: string) => {
        eq: (col: string, value: number) => {
          maybeSingle: () => Promise<{ data: GeographySnapshot | null }>;
        };
      };
    };
  })
    .from("geography_insights")
    .select("days, computed_at, from_date, total_first_authors, locations")
    .eq("days", days)
    .maybeSingle();

  if (snapshot) {
    const response = NextResponse.json({
      source: "precomputed",
      days: snapshot.days,
      asOf: snapshot.computed_at,
      fromDate: snapshot.from_date,
      totalFirstAuthors: snapshot.total_first_authors,
      locations: snapshot.locations ?? [],
    });
    response.headers.set("Cache-Control", CACHE_HEADER);
    return response;
  }

  // Fallback: compute live. Reached before the first cron run, or for a
  // non-standard `days` value the cron does not precompute.
  try {
    const result = await computeAuthorGeography(supabase, days);
    // Seed the snapshot so the next request takes the fast path without
    // waiting for the daily cron. Best-effort — never fails the response.
    await persistSnapshot(result);
    const response = NextResponse.json({
      source: "database",
      days: result.days,
      asOf: new Date().toISOString(),
      fromDate: result.fromDate,
      totalFirstAuthors: result.totalFirstAuthors,
      locations: result.locations,
    });
    response.headers.set("Cache-Control", CACHE_HEADER);
    return response;
  } catch (error) {
    console.error("[author-geography] live computation failed:", error);
    return NextResponse.json(
      { error: "Failed to fetch first-author affiliations." },
      { status: 500 }
    );
  }
}
